admin_user: devops

admin_authorized_key: ""

ssh_permit_root_login: "no"
ssh_password_authentication: "no"
ssh_pubkey_authentication: "yes"

allow_users:
  - "{{ admin_user }}"

ufw_allowed_ports:
  - 22
